name: Build PDF on Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-upload:
    name: Build and upload
    uses: ./.github/workflows/upload_release.yml
    secrets: inherit
